baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'RezzyTech'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'RezzyTech'

seo:
  meta_og_title: "RezzyTech"
  meta_og_type: "website"
  meta_og_url: "https://rezzytech.com"
  meta_og_description: "RezzyTech - we bring Innovation"
  meta_twitter_card: "summary"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact

plugins:
  - jekyll-environment-variables
